language: elixir
elixir:
- 1.5
otp_release:
- 20.0
sudo: false
addons:
  postgresql: '9.4'
before_script:
- psql -c 'create database peepchat_test;' -U postgres
deploy:
  provider: heroku
  api_key:
    secure: JVb0l4yecra7zR4GVx34XSVvE0qWSjncoJPID5DHuoR2ODUsUJv3CaKnnEuGu86K3ByYm6X0qOAMT/7Ih1a+Hi0nPBaRAoyrZTKGguGgv3UNAonIG81p5gnQJDgrsQ/nMV+tt4uH5csTD7CZyy2499ql5eH+QF18/bLS1hbBnQgdbG11Skgputy9B5rioyY7pTG+UKTj1SQCNtBwNVPQPELi9oAS2mUFSRxX5rLSAWGeN5tXMYYgxnDaBH0k8qA5y6MBxCTgF8e4ftIMwdXZncAUlZRTqtplnKBxCEvc0ITKBeXt4Fjnub7wl26uaBbmLQO2ZpcbH8ANk8p2ARN4rGaruJrrdmqE117dM+Y3Nm1a6AH9Wf9PeUHN9gpIVcJrWD5YxD9s1/pYHCVLx8zzx9ziVhb5z0cexd8LtAwbqOCaHwYdByD2aSK3xsjnOmgr6zE8MALO2NcklmhU/rNfr0MmOLMxjZbHfmkZvP9S+uOS2uE7SrWdWAZdAuk1+QnYA1SXTPTuqcUo/dtYcPDVc15BUFHEY+c1zHakfb5LeKBQzb+ATKTSjWpHbJmdyhdIaIGR7/3NabkbYj8bdNGEP01ONX0TeOaa590vSN+Uo/bV04BPgmgdtvf84FmaiVOvWORMmSmOAVEz2hp/5+sxSCzvc5HDK5pdbk1Pccp5Z50=
  app: evening-springs-26713
  on:
    repo: neanias/peepchat-api
